name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      
    steps:
    - uses: anthropics/claude-code-action@beta
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        trigger_phrase: "@claude-code"
